config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root "public_recipes#index"

  resources :public_recipes, only: [:index]

  resources :recipes, only: [:index]
  resources :users do 
    resources :recipes, except: [:update, :edit] do
      resources :recipe_foods, only: [:new]
      resources :shopping_list, only: [:index]
      
      resources :foods, only: [:index] do
        resources :recipe_foods, only: [ :create, :destroy]
      end
    end
    resources :foods, only: [:index, :create, :new, :destroy]

  end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(_user)
    user ||= User.new # guest user

    can :manage, :all if user.role? :admin
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ActiveRecord::Base
  belongs_to :food
  belongs_to :inventory
end

app/models/public_recipe.rb
class PublicRecipe < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def food_arr(recipe)
    food_arr = []
    recipe_foods = RecipeFood.where(recipe_id: recipe)

    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        food_arr.push(food)
      end
    end
    food_arr
  end

  def total_food_price(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @sigle_food_price = food.price * recipe_food.quantity
      end
      total += @sigle_food_price
    end
    total
  end
end

app/models/recipe_food.rb
class RecipeFood < ActiveRecord::Base
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  def total_price(ingredients)
    price = 0
    ingredients.each do |recipe_food|
      price += Food.find(recipe_food.food_id).price * recipe_food.quantity
    end
    price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Helpers

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

  # Overwriting the sign_out redirect path method
  def after_sign_up_path_for(_resource_or_scope)
    new_user_session
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def show
    @foods = Food.all.where(user_id: current_user.id)
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      flash[:success] = 'Food created succesfully'
      redirect_to user_foods_path

    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find_by(id: params[:id])
    @food.destroy
    flash[:success] = 'Food deleted'
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
    @public_recipe = Recipe.new

    # @total_recipe_price =
    # @recipe = Recipe.find(params[:id])
    # # @items_count= RecipeFood.where(food_id: => )
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_id = Recipe.find(params[:recipe_id]).id
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id]).id
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = Recipe.find(params[:recipe_id]).id
    @recipe_food.food_id = Food.find(params[:food_id]).id

    if @recipe_food.save
      flash[:success] = 'RecipeFood was succesfully created'
      redirect_to new_user_recipe_recipe_food_path(current_user.id, @recipe)
    else
      flash[:danger] = @recipe_food.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to user_recipe_path(current_user.id, @recipe.id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index; end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:success] = 'Recipe was succesfully created'
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    render recipes_path unless (@recipe.public == true) || (@recipe.user_id == current_user.id)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public, :cooking_time, :preparation_time)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
    @ingredients = RecipeFood.where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @ingredients.map(&:food_id))

    @total_price = ShoppingList.new.total_price(@ingredients)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    sign_out :user
    redirect_to
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  private

  def set_user
    @user = User.new(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1 class='text-center mb-3'> Foods </h1>


    <div class = 'col-8 d-flex flex-column margin-auto justify-content-center mx-auto'>

        <div class='align-center p-5' > <%= link_to 'New food', new_user_food_path(current_user.id), class: 'btn btn-primary text-center' %></div> 

        <table class="table">
        <thead>
            <tr>
            <th scope="col">Food</th>
            <th scope="col">Measurement Unit</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>

        <tbody>
        <% current_user.foods.each do |food| %>
            <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td><%= button_to "Delete Food", user_food_path(current_user.id, food.id), method: :delete, 
                    data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %> </td>
            
            </tr>
            <% end %>
        </tbody>


        </table>

    </div>

app/views/foods/new.html.erb
<h1 class='text-center mb-3'>New Food</h1>

<div class='mb-5'>
  <%= form_with(model: @food, url: user_foods_path) do |f| %>

      <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label :name, class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Enter food name", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex" >
      <%= f.label :measurement_unit, class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :measurement_unit, class:"form-control", placeholder: "Enter measurement unit (e.g: kg, l, unit", autofocus: true %>
      </div>
    </div>


    <div class= "form-group d-flex my-4" >
      <%= f.label :price, class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :price,   class:"form-control", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div>
  
  
  
  <% end %>
</div>

app/views/public_recipes/index.html.erb
<h1 class="text-center">Public recipes</h1>
  <% @public_recipes.each do |recipe| %>
  <div class="col-sm-8 border border-2 m-auto p-4 my-3 row"> 
    <div class="col-4  border-end border-2"> 



      <h5 class="my-3 pb-2 text-decoration-none"><%= link_to recipe.name, user_recipe_path( recipe.user.id, recipe.id  ) %> </h5>
      <p> By: <%= recipe.user.email %> </p>
      
    
    
    </div>

    <div class="col d-flex align-items-center flex-column justify-content-center px-4">

      <p>Total food items: <%=  @public_recipe.food_arr(recipe.id).count %></p>

      <p>Total price: 
        <%=  @public_recipe.total_food_price(@public_recipe.food_arr(recipe.id), recipe.id ) %>$
      </p>

    </div>  
 </div>
  <% end %>

app/views/recipe_foods/new.html.erb
<h1 class='text-center mb-3'> Foods </h1>
<div class = 'd-flex flex-column m-auto col-9 justify-content-center'>
	<div class='align-center py-3' > 
	<%= link_to 'New food', new_user_food_path(current_user.id), class: 'btn btn-outline-primary text-center' %>
	<%= link_to 'Back to recipe', user_recipe_path(current_user.id,  @recipe.id), class: 'btn btn-outline-primary text-center' %>
	
	</div> 
		
		<div class="row bg-secondary text-white p-2"> 
				<div class="col-3"> Food </div>
				<div class="col-3">	Measurement Unit</div>
				<div class="col-3">	Quantity</div>
				<div class="col-3">Actions</div>
		</div>

		<% @foods.each do |food| %>
				<%= form_with(model: @recipe_food, url:"/users/#{current_user.id}/recipes/#{@recipe_id}/foods/#{food.id}/recipe_foods"  ) do |f| %>
					<div class="row p-2 border border-1 p-4"> 
                        <%= food.errors.full_messages.join(", ") if food.errors.any? %>						<div class="col-3"> <%= food.name %> </div>
						<div class="col-3">	<%= food.measurement_unit%></div>
						<div class="col-3">	<%= f.number_field :quantity%></div>

						<div class="col-3"><%= f.submit class: "btn btn-sm btn-warning submit-btn"%></div>
					</div>
			<% end %>
		<% end %>
</div>

app/views/recipes/index.html.erb
<h1 class='text-center mb-3'> Your recipes</h1>

  <% current_user.recipes.each do |recipe| %>
  <div class="col-sm-7 border border-2 m-auto p-4 my-3 row"> 
    <div class="col-4  border-end border-2"> 
      <h3 class="my-3 pb-2"> <%= recipe.name %> </h3>
      <%= button_to "Delete", user_recipe_path(current_user.id, recipe), method: :delete, 
                                              data: {confirm: 'Are you sure that you want to delete this article?'}, class: "btn btn-primary" %>
    <div class = "py-2">
      <%= link_to 'See this recipe', user_recipe_path( recipe.user.id, recipe.id  )%>
    </div>

    </div>

    <div class="col d-flex align-items-center px-4">
      <p><%= recipe.description %></p>
    </div>
  
 </div>
  <% end %>

app/views/recipes/new.html.erb
<h1 class='text-center mb-3'> Create a new recipe</h1>
<div class="mb-5">  
  <%= form_with(model: @recipe, url: user_recipes_path(current_user.id)) do |f| %>
  <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label :name, class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Recipe name", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex" >
      <%= f.label :description, class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_area :description, rows: 4,   class:"form-control", placeholder: "Description of the recipe", autofocus: true %>
      </div>
    </div>


    <div class= "form-group d-flex my-4" >
      <%= f.label "Preparation time (min):", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :preparation_time,   class:"form-control", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex" >
      <%= f.label "Cooking time (min):", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :cooking_time,   class:"form-control", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex mt-4" >
      <%= f.label "Public:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class= "d-flex align-items-center">
      <%= f.check_box :public, class:"form-check-input form-control", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div>
  <% end %>
</div> 

 

app/views/recipes/show.html.erb
  <div class='col-sm-7 pb-2 mx-auto'>
    <h1 > <%= @recipe.name %></h1> 
    <small >by <%= @recipe.user.email %> </small> 
  </div>

<div class="col-sm-7 border m-auto p-4 mb-5"> 
  <div class="d-flex justify-content-between">
    <h4 class="py-3">Preparation time: <%= @recipe.preparation_time %> min</h4>
    <div class="form-check form-switch">
      
      <% if @recipe.public %>
        <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
        <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked disabled>
      <% else %>
        <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
        <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" disabled>
      <% end %>
   
    </div>
  </div>

  <h4 class="py-3">Cooking time: <%= @recipe.cooking_time %> min</h4>
  <h4 class="py-3">Steps: </h4>
  <p> <%= @recipe.description %> </p>

  <div class="d-flex justify-content-between py-4 mb-3">
    <%= link_to "Generate shopping list", user_recipe_shopping_list_index_path(current_user.id, @recipe.id),class: "btn btn-outline-primary"%> 
    <%= link_to "Add ingredients",  new_user_recipe_recipe_food_path(current_user.id, @recipe.id), class: "btn btn-outline-primary" %>
  </div>

  <% if @recipe_foods.any? %>

     <div class="row bg-secondary text-white border-bottom p-2">
        <div class="col-3" >Food</div>
        <div class="col-2">Quantity </div>
        <div class="col-3">Value </div>
        <div class="col-4">Actions</div>
    </div>
    

      <% @recipe_foods.each do |recipe_food| %>
      <% food = Food.find(recipe_food.food_id) %>
      <div class="row border-bottom border-2 p-3">
        <div class="col-3"> <%= Food.find(recipe_food.food_id).name %> </div>
        <div class="col-2"> <%= recipe_food.quantity %></div>
        <div class="col-3"> <%= food.measurement_unit %></div>
        <div class="col-4 d-flex"> 
          <%= link_to "Modify","/foods",  class: "btn btn-sm btn-success disabled" %>
          <%= button_to "Delete", user_recipe_food_recipe_food_path(current_user.id, @recipe.id, food.id, recipe_food.id), method: :delete, 
                  data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-primary mx-4" %>
        </div>
      </div>
      <% end %>
      <% end %>
</div>

app/views/shopping_list/index.html.erb
 
  <div class='col-sm-7 pb-2 mx-auto'>
    <h1 class="text-center" >Shopping list</h1> 
  </div>

  <div class='col-sm-7 pb-2 mx-auto d-flex justify-content-between'>
    <p>Amount of food items: <%= @ingredients.count %> </p>
    <p>Total value of food needed: <%= @total_price %>$
     </p>
  </div>

 <div class="col-sm-7 border m-auto p-4 mb-5 "> 
  <div class="row bg-secondary text-white p-1">
    <div class="col-4" >Food</div>
    <div class="col-4">Quantity </div>
    <div class="col-4">Price </div>

  </div>

  <% @ingredients.each do |recipe_food| %>
  <% food = Food.find(recipe_food.food_id) %>
  <div class="row">
  <div class="row border-bottom border-2 m-2 p-2 ">
    <div class="col-4"> <%= Food.find(recipe_food.food_id).name %> </div>
    <div class="col-4"> <%= recipe_food.quantity %> <%= food.measurement_unit %></div>
    <div class="col-4"><%= Food.find(recipe_food.food_id).price * recipe_food.quantity%> $</div>
  </div>
   </div>
  <% end %>
  </div>
 