config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root "public_recipes#index"

  resources :public_recipes, only: [:index]

  resources :recipes, only: [:index]
  resources :users do 
    resources :recipes, except: [:update, :edit] do
      resources :recipe_foods, only: [:new]
      resources :shopping_list, only: [:index]
      
      resources :foods, only: [:index] do
        resources :recipe_foods, only: [ :create, :destroy]
      end
    end
    resources :foods, only: [:index, :create, :new, :destroy]

  end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(_user)
    user ||= User.new # guest user

    can :manage, :all if user.role? :admin
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ActiveRecord::Base
  belongs_to :food
  belongs_to :inventory
end

app/models/public_recipe.rb
class PublicRecipe < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def food_arr(recipe)
    food_arr = []
    recipe_foods = RecipeFood.where(recipe_id: recipe)

    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        food_arr.push(food)
      end
    end
    food_arr
  end

  def total_food_price(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @sigle_food_price = food.price * recipe_food.quantity
      end
      total += @sigle_food_price
    end
    total
  end
end

app/models/recipe_food.rb
class RecipeFood < ActiveRecord::Base
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  def total_price(ingredients)
    price = 0
    ingredients.each do |recipe_food|
      price += Food.find(recipe_food.food_id).price * recipe_food.quantity
    end
    price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Helpers

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

  # Overwriting the sign_out redirect path method
  def after_sign_up_path_for(_resource_or_scope)
    new_user_session
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def show
    @foods = Food.all.where(user_id: current_user.id)
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      flash[:success] = 'Food created succesfully'
      redirect_to user_foods_path

    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find_by(id: params[:id])
    @food.destroy
    flash[:success] = 'Food deleted'
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_id = Recipe.find(params[:recipe_id]).id
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id]).id
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = Recipe.find(params[:recipe_id]).id
    @recipe_food.food_id = Food.find(params[:food_id]).id

    if @recipe_food.save
      flash[:success] = 'RecipeFood was succesfully created'
      redirect_to new_user_recipe_recipe_food_path(current_user.id, @recipe)
    else
      flash[:danger] = @recipe_food.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to user_recipe_path(current_user.id, @recipe.id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index; end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:success] = 'Recipe was succesfully created'
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    render recipes_path unless (@recipe.public == true) || (@recipe.user_id == current_user.id)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :public, :cooking_time, :preparation_time)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
    @ingredients = RecipeFood.where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @ingredients.map(&:food_id))

    @total_price = ShoppingList.new.total_price(@ingredients)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    sign_out :user
    redirect_to
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  private

  def set_user
    @user = User.new(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
    <div class="row d-flex justify-content-center" >
      <div class="col-sm-8" >

          <% flash.each do |name, msg|%>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <%= content_tag :div, msg, :id =>  "flash_#{name}" if msg.is_a?(String)%>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div >
          <% end %>

      </div>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="w-full d-flex justify-content-between px-4" id="navbarSupportedContent">
  <% if user_signed_in? %>
  <ul class="navbar-nav mr-auto">
    <li> <%= link_to 'Public recipes', root_path, class: 'nav-link' %></li> 
    <li> <%= link_to 'New recipe', new_user_recipe_path(user_id: current_user.id), class: 'nav-link' %></li> 
    <li> <%= link_to 'My Recipes', user_recipes_path(user_id: current_user.id), class: 'nav-link' %></li> 
    <li> <%= link_to 'Foods', user_foods_path(current_user.id), class: 'nav-link' %> </li>
  </ul>

  <ul class="navbar-nav mr-auto">
    <li><%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'nav-link' %></li>
  </ul>

  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <% if flash.any? %>
        <%= render 'layouts/messages' %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class='text-center'> Homepage</h1>